#!/bin/bash

#DIR="$(dirname "$0")"
KEYS="$DIR/data/keys.list"
REPOS="$DIR/data/repos.list"
DEPS="$DIR/data/dependencies.list"
PKGS="$DIR/data/packages.list"

RPKGS="$DIR/data/rpackages.list"
CRAN="https://cran.r-project.org"
RLIBLOC="/usr/local/lib/R/site-library/"

RPKGS="$DIR/data/pypackages.list"

apt-get install lsb-release
UB_VER=$(lsb_release -cs)
